### PR TITLE
[apps/code] Fix Key selector in auto completion

### LINKED ISSUE #198: [apps/python] Key selector is showed in autocompletion
**Describe the bug**
When you type “K” with the `ion` module imported, the autocompletion show “Key selector” as suggestion

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Python app
2. Create a new script
3. Type 
```python
from ion import *
K
```
4. See error.

**Expected behaviour**
Key selector shouldn't appear in the autocompletion

**Screenshots**
image

**Device:**
 - Devices : My calculator and the Web simulator (I think all platforms are concerned…)
 - Upsilon Version: 1.0.0-dev
 - Upsilon commit: a770ee9

### PR DESCRIPTION
**Pull request by Yaya-Cout**
Scenario: Go in the Python editor and type `from ion import *`,
                then type `K` and see what happens.
This fix #198. This pull request also restore the old keys behaviour in a new submenu.

### CODE REVIEW

File: apps/code/python_toolbox.cpp [hunk 1]
```diff
@@ -728,6 +775,24 @@ bool PythonToolbox::selectLeaf(int selectedRow, bool quitToolbox) {
...
+    Container::activeApp()->displayModalViewController(static_cast<ViewController*>(&m_ionKeys), 0.f, 0.f, Metric::PopUpTopMargin, Metric::PopUpLeftMargin, 0, Metric::PopUpRightMargin);
+    return true;
+  }
+  m_selectableTableView.deselectTable();
+  m_messageTreeModel = static_cast<const ToolboxMessageTree *>(m_messageTreeModel->childAtIndex(selectedRow));
+  if (m_messageTreeModel->isFork()) {
+    assert(m_messageTreeModel->numberOfChildren() < 0);
+    m_messageTreeModel = static_cast<const ToolboxMessageTree *>(m_messageTreeModel->childAtIndex(indexAfterFork()));
+  }
+  return NestedMenuController::selectSubMenu(selectedRow);
```
Comment (Lauryy06) [inline apps/code/python_toolbox.cpp]: Why do not call the super implementation ?

Comment (Yaya-Cout) [reply apps/code/python_toolbox.cpp]: How ?
