### PR TITLE
[bootloader/storage] new bootloader and fix python issue

### LINKED ISSUE #209: Impossible to build binpack
**Describe the bug**
When trying to build binpack, it returns an error: "file maybe already patched"

**To Reproduce**
Build latest upsilon-dev or just look at the [CI/CD](https://github.com/UpsilonNumworks/Upsilon/runs/5804868020?check_suite_focus=true)

**Expected behavior**
I really don't understand what's happening. Maybe that having bootloader binpack make make go like there's too much.
**Screenshots**

**Device (please complete the following information):**
-binpack for n0110
-latest upsilon: [5365718](https://github.com/UpsilonNumworks/Upsilon/commit/5365718761013db0c9fe707e9224f6f02f99f16e)

### PR DESCRIPTION
**Pull request by devdl11**
An amazing Upsilon Bootloader ! 
Thanks @Yaya-Cout for helping me bring this beauty to life ;-)  
I also fix by the way the python issue

### CODE REVIEW

File: bootloader/itoa.cpp [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+    // With any other base, value is always considered unsigned
+    if (value < 0 && base == 10) {
+        buffer[i++] = '-';
+    }
+ 
+    buffer[i] = '\0'; // null terminate string
+ 
+    // reverse the string and return it
+    return reverse(buffer, 0, i - 1);
+}
```
Comment (Lauryy06) [inline bootloader/itoa.cpp]:
```suggestion
}

```

File: bootloader/itoa.cpp [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+// https://www.techiedelight.com/implement-itoa-function-in-c/
+
+// Function to swap two numbers
+void swap(char *x, char *y) {
+    char t = *x; *x = *y; *y = t;
+}
+ 
+// Function to reverse `buffer[i…j]`
+char* reverse(char *buffer, int i, int j)
+{
```
Comment (Lauryy06) [inline bootloader/itoa.cpp]:
```suggestion
char* reverse(char *buffer, int i, int j) {
```

File: bootloader/itoa.cpp [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+    while (i < j) {
+        swap(&buffer[i++], &buffer[j--]);
+    }
+ 
+    return buffer;
+}
+ 
+// Iterative function to implement `itoa()` function in C
+char* Bootloader::Utility::itoa(int value, char* buffer, int base)
+{
```
Comment (Lauryy06) [inline bootloader/itoa.cpp]:
```suggestion
char* Bootloader::Utility::itoa(int value, char* buffer, int base) {
```

File: bootloader/itoa.cpp [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+    if (base < 2 || base > 32) {
+        return buffer;
+    }
+ 
+    // consider the absolute value of the number
+    int n = abs(value);
+ 
+    int i = 0;
+    while (n)
+    {
```
Comment (Lauryy06) [inline bootloader/itoa.cpp]:
```suggestion
    while (n) {
```

File: bootloader/itoa.h [hunk 5]
```diff
@@ -0,0 +1,11 @@
+#ifndef _BOOTLOADER_ITOA_H_
+#define _BOOTLOADER_ITOA_H_
+
+namespace Bootloader {
+    class Utility {
```
Comment (Lauryy06) [inline bootloader/itoa.h]: You don't need a class, I think just a namespace is enough (like for UTF8Helper).

File: bootloader/itoa.h [hunk 6]
```diff
@@ -0,0 +1,11 @@
...
+        public:
+            static char * itoa(int value, char * result, int base);
+    };
+}
+
+#endif // _BOOTLOADER_ITOA_H_
```
Comment (Lauryy06) [inline bootloader/itoa.h]:
```suggestion
#endif

```

File: bootloader/kernel_header.cpp [hunk 7]
```diff
@@ -22,4 +22,18 @@ const void(*KernelHeader::startPointer() const)() {
...
+    sum += m_version[i] * (5 - i);
+  }
+  char newVersion[] = "16";
+  int min = 0;
+  for (int i = 0; i < 2; i++) {
+    min += newVersion[i] * (5 - i);
+  }
+  return sum >= min;
+}
+
```
Comment (Lauryy06) [inline bootloader/kernel_header.cpp]: Maybe you can write a function like `versionSum()` to don't have copy-pasted code.
Also the name of the method is not explicit, I think that `isAboveVersion16` is better

File: bootloader/usb_data.cpp [hunk 8]
```diff
@@ -0,0 +1,39 @@
...
+    return USBData("@Flash/0x90000000/08*004Kg,01*032Kg,63*064Kg,64*064Kg", Messages::upsilonBootloader, DFUData());
+}
+
+const Bootloader::USBData Bootloader::USBData::BOOTLOADER_UPDATE() {
+    return USBData("@Flash/0x08000000/04*016Kg", Messages::bootloaderUpdate, DFUData(true, false));
+}
+
+Bootloader::USBData Bootloader::USBData::Recovery(uint32_t startAddress, uint32_t size) {
+    return USBData(buildStringDescriptor(StringHeader::SRAM(), startAddress, size), Messages::upsilonRecovery, DFUData(false, false));
+}
```
Comment (Lauryy06) [inline bootloader/usb_data.cpp]:
```suggestion
}

```

File: bootloader/usb_data.cpp [hunk 9]
```diff
@@ -0,0 +1,39 @@
...
+    data[strlen(header.getString()) + 8 + 3] = '*';
+    data[strlen(header.getString()) + 8 + 4] = '0';
+    Bootloader::Utility::itoa((int32_t)size/1024, &data[strlen(header.getString()) + 8 + 5], 10);
+    data[strlen(header.getString()) + 8 + 5 + 2] = 'K';
+    data[strlen(header.getString()) + 8 + 5 + 2 + 1] = 'g';
+    data[strlen(header.getString()) + 8 + 5 + 2 + 2] = '\0';
+    return &data[0];
+}
+
+const Bootloader::USBData Bootloader::USBData::DEFAULT() {
```
Comment (Lauryy06) [inline bootloader/usb_data.cpp:29]: Why capital letters ?

File: bootloader/usb_data.cpp [hunk 10]
```diff
@@ -0,0 +1,39 @@
...
+    return USBData("@Flash/0x90000000/08*004Kg,01*032Kg,63*064Kg,64*064Kg", Messages::upsilonBootloader, DFUData());
+}
+
+const Bootloader::USBData Bootloader::USBData::BOOTLOADER_UPDATE() {
```
Comment (Lauryy06) [inline bootloader/usb_data.cpp:33]: Here also.

File: bootloader/usb_data.h [hunk 11]
```diff
@@ -0,0 +1,56 @@
+#ifndef BOOTLOADER_USB_DATA_H_
+#define BOOTLOADER_USB_DATA_H_
+
+#include <stdint.h>
+#include <stddef.h>
+
+namespace Bootloader {
+
+class DFUData {
```
Comment (Lauryy06) [inline bootloader/usb_data.h]: I think `ProtectionState` or something like this is more appropriate.

File: bootloader/userland_header.cpp [hunk 12]
```diff
@@ -14,7 +14,7 @@ const bool UserlandHeader::isValid() const {
 }
 
 const bool UserlandHeader::isOmega() const {
-  return m_omegaMagicHeader == OmegaMagic && m_omegaMagicFooter == OmegaMagic;
+  return m_ohm_header == OmegaMagic && m_ohm_footer == OmegaMagic;
```
Comment (Lauryy06) [inline bootloader/userland_header.cpp]: why ?

File: build/device/secure_ext.py [hunk 13]
```diff
@@ -3,6 +3,8 @@
 
 MAGIK_CODE = [0x32, 0x30, 0x30, 0x36]
 MAGIK_POS = 0x44F
+# Disable Script
+sys.exit(0)
```
Comment (Lauryy06) [inline build/device/secure_ext.py:7]: I don't understand...

File: ion/src/device/shared/usb/stack/descriptor/platform_device_capability_descriptor.h [hunk 14]
```diff
@@ -1,5 +1,5 @@
-#ifndef ION_DEVICE_SHARED_USB_STACK_PLATFORM_DEVICE_CAPABILITY_DESCRIPTOR_H
-#define ION_DEVICE_SHARED_USB_STACK_PLATFORM_DEVICE_CAPABILITY_DESCRIPTOR_H
+#ifndef ION_DEVICE_SHARED_USB_STACK_PLATFORM_DEVICE_CAPABLITY_DESCRIPTOR_H
+#define ION_DEVICE_SHARED_USB_STACK_PLATFORM_DEVICE_CAPABLITY_DESCRIPTOR_H
```
Comment (Lauryy06) [inline ion/src/device/shared/usb/stack/descriptor/platform_device_capability_descriptor.h]: Why ?

File: ion/src/device/shared/usb/stack/descriptor/device_capability_descriptor.h [hunk 15]
```diff
@@ -1,5 +1,5 @@
-#ifndef ION_DEVICE_SHARED_USB_STACK_DEVICE_CAPABILITY_DESCRIPTOR_H
-#define ION_DEVICE_SHARED_USB_STACK_DEVICE_CAPABILITY_DESCRIPTOR_H
+#ifndef ION_DEVICE_SHARED_USB_STACK_DEVICE_CAPABLITY_DESCRIPTOR_H
+#define ION_DEVICE_SHARED_USB_STACK_DEVICE_CAPABLITY_DESCRIPTOR_H
```
Comment (Lauryy06) [inline ion/src/device/shared/usb/stack/descriptor/device_capability_descriptor.h]: Why ?

File: ion/src/device/bootloader/usb/stack/descriptor/descriptor.h [hunk 16]
```diff
@@ -0,0 +1,32 @@
...
+  friend class InterfaceDescriptor;
+public:
+  constexpr Descriptor(uint8_t bDescriptorType) :
+    m_bDescriptorType(bDescriptorType)
+  {
+  }
+  uint8_t type() const { return m_bDescriptorType; }
+protected:
+  void push(Channel * c) const override;
+  virtual uint8_t bLength() const { return 2*sizeof(uint8_t); }
```
Comment (Lauryy06) [inline ion/src/device/bootloader/usb/stack/descriptor/descriptor.h:22]: What means this name ?

File: ion/src/device/n0110/drivers/board.cpp [hunk 17]
```diff
@@ -106,7 +104,7 @@ void initMPU() {
    * then an AHB error is given (AN4760). To prevent this to happen, we
    * configure the MPU to define the whole Quad-SPI addressable space as
    * strongly ordered, non-executable and not accessible. Plus, we define the
-   * Quad-SPI region corresponding to the External Chip as executable and
+   * Quad-SPI region corresponding to the Expternal Chip as executable and
```
Comment (Lauryy06) [inline ion/src/device/n0110/drivers/board.cpp]: what is "expternal" exactly ?

File: ion/src/device/shared/drivers/display.cpp [hunk 18]
```diff
@@ -51,7 +51,7 @@ bool waitForVBlank() {
   uint64_t startTime = Timing::millis();
   uint64_t timeout = startTime + timeoutDelta;
 
-  /* If current time is big enough, currentTime + timeout wraps around the
+  /* If current time is big enough, currentTime + timeout wraps aroud the
```
Comment (Lauryy06) [inline ion/src/device/shared/drivers/display.cpp]: ?

File: ion/src/device/shared/drivers/reset.cpp [hunk 19]
```diff
@@ -49,7 +49,7 @@ void jump(uint32_t jumpIsrVectorAddress) {
   // Disable cache before reset
   Ion::Device::Cache::disable();
 
-  /* Shutdown all clocks and peripherals to mimic a hardware reset. */
+  /* Shutdown all clocks and periherals to mimic a hardware reset. */
```
Comment (Lauryy06) [inline ion/src/device/shared/drivers/reset.cpp]: ?

File: ion/src/device/shared/drivers/wakeup.h [hunk 20]
```diff
@@ -8,7 +8,7 @@ namespace Device {
 namespace WakeUp {
 
 /* All wakeup functions can be called together without overwriting the same
- * register. All together, they will set SYSCFG and EXTi registers as follow:
+ * register. All togethed, they will set SYSCFG and EXTi registers as follow:
```
Comment (Lauryy06) [inline ion/src/device/shared/drivers/wakeup.h]: ?

File: ion/src/device/shared/regs/tim.h [hunk 21]
```diff
@@ -17,7 +17,7 @@ class TIM {
   };
 
   class CCMR : Register64 {
-    /* We're declaring CCMR as a 64 bits register. CCMR doesn't exist per se,
+    /* We're declaring CCMR as a 64 bits register. CCMR doesn't exsist per se,
```
Comment (Lauryy06) [inline ion/src/device/shared/regs/tim.h]: ?

File: ion/src/device/shared/usb/calculator.h [hunk 22]
```diff
@@ -155,7 +155,7 @@ class Calculator : public Device {
   ExtendedCompatIDDescriptor m_extendedCompatIdDescriptor;
 
   Descriptor * m_descriptors[8];
-  /* m_descriptors contains only descriptors that should be returned via the
+  /* m_descriptors contains only descriptors that sould be returned via the
```
Comment (Lauryy06) [inline ion/src/device/shared/usb/calculator.h]: ?

File: build/device/secure_ext.py (hunk 13 above)
Comment (devdl11) [reply build/device/secure_ext.py:7]: We no longer use this type of protection because there is no longer an external/internal part but only bootloader and slots

File: bootloader/usb_data.cpp (hunk 9 above)
Comment (devdl11) [reply bootloader/usb_data.cpp:29]: Because it's a constant

File: bootloader/usb_data.cpp (hunk 10 above)
Comment (devdl11) [reply bootloader/usb_data.cpp:33]: same here

File: bootloader/itoa.h (hunk 5 above)
Comment (devdl11) [reply bootloader/itoa.h]: Yeah but maybe we will add some others useful functions ^^

File: ion/src/device/shared/usb/stack/descriptor/platform_device_capability_descriptor.h (hunk 14 above)
Comment (devdl11) [reply ion/src/device/shared/usb/stack/descriptor/platform_device_capability_descriptor.h]: Bulk copy paste mistake ^^'

File: ion/src/device/shared/usb/stack/descriptor/device_capability_descriptor.h (hunk 15 above)
Comment (devdl11) [reply ion/src/device/shared/usb/stack/descriptor/device_capability_descriptor.h]: Bulk copy paste mistake ^^'

File: ion/src/device/bootloader/usb/stack/descriptor/descriptor.h (hunk 16 above)
Comment (devdl11) [reply ion/src/device/bootloader/usb/stack/descriptor/descriptor.h:22]: I don't know it's the same usb code as in the shared directory.

File: ion/src/device/n0110/drivers/board.cpp (hunk 17 above)
Comment (devdl11) [reply ion/src/device/n0110/drivers/board.cpp]: Same as the previous one, bulk copy paste mistake ^^' I developed the bootloader within the Omega 2.0 repository and I just copied paste the modified directories without checking ^^'

File: bootloader/itoa.h (hunk 5 above)
Comment (Lauryy06) [reply bootloader/itoa.h]: Yes but as all utility functions are or will be static, a class is not necessary.

File: bootloader/messages.h [hunk 23]
```diff
@@ -0,0 +1,60 @@
+#ifndef BOOTLOADER_INTERFACE_MESSAGES_H
+#define BOOTLOADER_INTERFACE_MESSAGES_H
+
+namespace Bootloader {
+
+class Messages {
+public:
+  // TODO: Remove it when this fork will be updated
+  #define UPSILON_VERSION "1.0.0-dev"
```
Comment (Yaya-Cout) [inline bootloader/messages.h]: Remove it.
```suggestion
```

File: bootloader/messages.h [hunk 24]
```diff
@@ -0,0 +1,60 @@
...
+  
+  constexpr static const char * upsilonBootloader = "Upsilon Bootloader";
+  constexpr static const char * upsilonRecovery = "Upsilon Recovery";
+  constexpr static const char * bootloaderUpdate = "Bootloader Update";
+
+};
+
+};
+
+#endif
```
Comment (Yaya-Cout) [inline bootloader/messages.h]: Add newline
```suggestion
#endif

```

File: bootloader/usb_data.h [hunk 25]
```diff
@@ -0,0 +1,56 @@
...
+
+  private:
+    const char * m_stringDescriptor;
+    const char * m_name;
+    ProtectionState * m_data;
+
+};
+}
+
+#endif //BOOTLOADER_USB_DATA_H_
```
Comment (Yaya-Cout) [inline bootloader/usb_data.h]: Add newline.
```suggestion
#endif //BOOTLOADER_USB_DATA_H_

```

File: build/device/secure_ext.py (hunk 13 above)
Comment (Yaya-Cout) [reply build/device/secure_ext.py:7]: Yes, but why are you not removing it from the Makefile ?

File: ion/src/device/bootloader/usb/Makefile [hunk 26]
```diff
@@ -0,0 +1,99 @@
...
+$(BUILD_DIR)/ion/src/device/bootloader/usb/dfu.o: $(BUILD_DIR)/ion/src/device/bootloader/usb/dfu.bin
+	$(call rule_label,OBJCOPY)
+	$(Q) cd $(dir $<) ; $(OBJCOPY) -I binary -O elf32-littlearm -B arm --rename-section .data=.rodata.dfu_bootloader --redefine-sym _binary_dfu_bin_start=_dfu_bootloader_flash_start --redefine-sym _binary_dfu_bin_end=_dfu_bootloader_flash_end $(notdir $<) $(notdir $@)
+
+ion_device_src += ion/src/device/bootloader/usb/dfu.cpp:-usbxip
+ion_device_src += ion/src/device/bootloader/usb/dfu_relocated.cpp:-usbxip
+
+ion_device_src += $(addprefix ion/src/device/bootloader/drivers/, \
+  usb_desc.cpp \
+)
```
Comment (Yaya-Cout) [inline ion/src/device/bootloader/usb/Makefile]: Add newline.
```suggestion
)

```

File: ion/src/device/flasher/display_light.cpp [hunk 27]
```diff
@@ -1,16 +1,10 @@
...
 namespace Display {
 
 void init() {
-  KDRect screen = KDRect(0,0,Ion::Display::Width,Ion::Display::Height);
-  Ion::Display::pushRectUniform(KDRect(0,0,Ion::Display::Width,Ion::Display::Height), KDColor::RGB24(0x5e81ac));
-  KDContext * ctx = KDIonContext::sharedContext();
-  ctx->setOrigin(KDPointZero);
-  ctx->setClippingRect(screen);
-  ctx->drawString("RECOVERY MODE", KDPoint(10, 10), KDFont::LargeFont, KDColorWhite, KDColor::RGB24(0x5e81ac));
+  Ion::Display::pushRectUniform(KDRect(0,0,Ion::Display::Width,Ion::Display::Height), KDColor::RGB24(0xFFFF00));
```
Comment (Yaya-Cout) [inline ion/src/device/flasher/display_light.cpp]: Why are you editing this ?

File: ion/src/device/flasher/display_verbose.cpp [hunk 28]
```diff
@@ -1,55 +1,47 @@
...
-            for (int i = 1; i < sNumberOfMessages; ++i) {
-                message = sMessages[i];
-                KDSize messageSize = KDFont::SmallFont->stringSize(message);
-                ctx->drawString(message, KDPoint((Ion::Display::Width-messageSize.width())/2, currentHeight),
-                                KDFont::SmallFont, KDColorWhite, KDColor::RGB24(0x2B2B2B));
-                currentHeight += messageSize.height();
-            }
-        }
-
+namespace Display {
```
Comment (Yaya-Cout) [inline ion/src/device/flasher/display_verbose.cpp]: Why are you editing it ?

File: ion/src/device/n0100/flash.ld [hunk 29]
```diff
@@ -71,7 +71,7 @@ SECTIONS {
     /* The data section is written to Flash but linked as if it were in RAM.
      *
      * This is required because its initial value matters (so it has to be in
-     * persistent memory in the first place), but it is a R/W area of memory
+     * persistant memory in the first place), but it is a R/W area of memory
```
Comment (Yaya-Cout) [inline ion/src/device/n0100/flash.ld]: Why do you edit it ?
```suggestion
     * persistent memory in the first place), but it is a R/W area of memory
```

File: ion/src/device/n0110/drivers/board.cpp [hunk 30]
```diff
@@ -64,7 +62,7 @@ void initMPU() {
   /* This is needed for interfacing with the LCD
    * We define the whole FMC memory bank 1 as strongly ordered, non-executable
    * and not accessible. We define the FMC command and data addresses as
-   * writeable non-cacheable, non-buffereable and non shareable. */
+   * writeable non-cachable, non-buffereable and non shareable. */
```
Comment (Yaya-Cout) [inline ion/src/device/n0110/drivers/board.cpp]: Why are you editing it ?
```suggestion
   * writeable non-cacheable, non-buffereable and non shareable. */
```

File: ion/src/device/n0110/internal_flash.ld [hunk 31]
```diff
@@ -64,7 +64,7 @@ SECTIONS {
     /* The data section is written to Flash but linked as if it were in RAM.
      *
      * This is required because its initial value matters (so it has to be in
-     * persistent memory in the first place), but it is a R/W area of memory
+     * persistant memory in the first place), but it is a R/W area of memory
```
Comment (Yaya-Cout) [inline ion/src/device/n0110/internal_flash.ld]: Why are you editing it ?
```suggestion
     * persistent memory in the first place), but it is a R/W area of memory
```

File: ion/src/device/shared/drivers/battery.cpp [hunk 32]
```diff
@@ -4,10 +4,10 @@
 
 /* To measure the battery voltage, we're using the internal ADC. The ADC works
  * by comparing the input voltage to a reference voltage. The only fixed voltage
- * we have around is 2.8V, so that's the one we're using as a reference. However,
+ * we have around is 2.8V, so that's the one we're using as a refrence. However,
  * and ADC can only measure voltage that is lower than the reference voltage. So
  * we need to use a voltage divider before sampling Vbat.
- * To avoid draining the battery, we're using a high-impedance voltage divider,
+ * To avoid draining the battery, we're using an high-impedence voltage divider,
```
Comment (Yaya-Cout) [inline ion/src/device/shared/drivers/battery.cpp:10]: Why are you editing it ?

File: ion/src/device/shared/drivers/exam_mode.cpp [hunk 33]
```diff
@@ -51,28 +51,28 @@ size_t numberOfBitsAfterLeadingZeroes(int i) {
 }
 
 uint8_t * SignificantExamModeAddress() {
-  uint32_t * persistence_start_32 = (uint32_t *)&_exam_mode_buffer_start;
-  uint32_t * persistence_end_32 = (uint32_t *)&_exam_mode_buffer_end;
-  assert((persistence_end_32 - persistence_start_32) % 4 == 0);
-  while (persistence_start_32 < persistence_end_32 && *persistence_start_32 == 0x0) {
+  uint32_t * persitence_start_32 = (uint32_t *)&_exam_mode_buffer_start;
```
Comment (Yaya-Cout) [inline ion/src/device/shared/drivers/exam_mode.cpp:54]: Why do you edit it ?

File: ion/src/device/shared/usb/dfu.ld [hunk 34]
```diff
@@ -1,5 +1,5 @@
 /* DFU transfers can serve two purposes:
- *  - Transferring RAM data between the machine and the host, e.g. Python scripts
+ *  - Transfering RAM data between the machine and the host, e.g. Python scripts
```
Comment (Yaya-Cout) [inline ion/src/device/shared/usb/dfu.ld]: Why do you edit it ?
```suggestion
 *  - Transferring RAM data between the machine and the host, e.g. Python scripts
```

File: ion/src/device/shared/usb/dfu_interface.h [hunk 35]
```diff
@@ -70,11 +54,10 @@ class DFUInterface : public Interface {
     GetStatus    = 3,
     ClearStatus  = 4,
     GetState     = 5,
-    Abort        = 6,
-    Unlock       = 11
+    Abort        = 6
   };
 
-  // DFU Download Command Codes
+  // DFU Download Commmand Codes
```
Comment (Yaya-Cout) [inline ion/src/device/shared/usb/dfu_interface.h]: Why do you edit it ?
```suggestion
  // DFU Download Command Codes
```

File: ion/src/device/shared/usb/dfu_relocated.cpp [hunk 36]
```diff
@@ -59,7 +59,7 @@ void DFU(bool exitWithKeyboard, bool unlocked, int level) {
 
   /* 4- Disable all interrupts
    * The interrupt service routines live in the Flash and could be overwritten
-   * by garbage during a firmware upgrade operation, so we disable them. */
+   * by garbage during a firmware upgrade opration, so we disable them. */
```
Comment (Yaya-Cout) [inline ion/src/device/shared/usb/dfu_relocated.cpp]: Why do you edit it ?
```suggestion
   * by garbage during a firmware upgrade operation, so we disable them. */
```

File: ion/src/device/shared/usb/stack/device.cpp [hunk 37]
```diff
@@ -108,7 +108,7 @@ bool Device::processSetupInRequest(SetupPacket * request, uint8_t * transferBuff
     case (int) Request::GetStatus:
       return getStatus(transferBuffer, transferBufferLength, transferBufferMaxLength);
     case (int) Request::SetAddress:
-      // Make sure the request is address is valid.
+      // Make sure the request is adress is valid.
```
Comment (Yaya-Cout) [inline ion/src/device/shared/usb/stack/device.cpp]:
```suggestion
      // Make sure the request is address is valid.
```

File: ion/src/device/flasher/display_light.cpp (hunk 27 above)
Comment (devdl11) [reply ion/src/device/flasher/display_light.cpp]: Ahhh yeah you're right I screwed up with the merger between omega and upsilon

File: ion/src/device/shared/drivers/reset.cpp (hunk 19 above)
Comment (darthnithin) [reply ion/src/device/shared/drivers/reset.cpp]: ? Changed correct spelling to wrong spelling

File: bootloader/boot.h [hunk 38]
```diff
@@ -19,10 +35,26 @@ class Boot {
...
+
+  static void bootloader();
+  static void lockInternal();
+  static void enableFlashIntr();
 };
 
+
 }
 
 #endif
```
Comment (Yaya-Cout) [inline bootloader/boot.h]: Add newline
```suggestion
#endif

```

File: bootloader/drivers/stm32_drivers.h [hunk 39]
```diff
@@ -0,0 +1,153 @@
...
+
+  #define STM_32_RCC ((STM32::STM32_RCC_TypeDef *) RCC_BASE)
+  #define STM_32_SysTick ((STM32::STM32_SysTick_Type *) SysTick_BASE)
+  #define STM_32_NVIC ((STM32::STM32_NVIC_Type *) NVIC_BASE)
+  #define STM_32_SCB ((STM32_SCB_Type *) SCB_BASE)
+
+  extern void rcc_deinit();
+  extern void hal_deinit();
+  extern void systick_deinit();
+}
```
Comment (Yaya-Cout) [inline bootloader/drivers/stm32_drivers.h]: Add newline
```suggestion
}

```

File: bootloader/interface/menus/about.cpp [hunk 40]
```diff
@@ -0,0 +1,20 @@
...
+    m_default_columns[2] = Column(Messages::aboutMessage3, k_small_font, 0, true);
+    m_default_columns[3] = Column(Messages::aboutMessage4, k_small_font, 0, true);
+    m_default_columns[4] = Column(Messages::aboutMessage5, k_small_font, 0, true);
+
+    m_columns[0] = ColumnBinder(&m_default_columns[0]);
+    m_columns[1] = ColumnBinder(&m_default_columns[1]);
+    m_columns[2] = ColumnBinder(&m_default_columns[2]);
+    m_columns[3] = ColumnBinder(&m_default_columns[3]);
+    m_columns[4] = ColumnBinder(&m_default_columns[4]);
+}
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/about.cpp]: Add newline
```suggestion
}

```

File: bootloader/interface/menus/about.h [hunk 41]
```diff
@@ -0,0 +1,17 @@
...
+    public:
+      AboutMenu();
+    
+      void setup() override;
+      void post_open() override {};
+  };
+}
+
+
+#endif
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/about.h]: Add newline
```suggestion
#endif

```

File: bootloader/interface/menus/crash.cpp [hunk 42]
```diff
@@ -0,0 +1,22 @@
...
+  m_columns[1] = ColumnBinder(&m_default_columns[1]);
+  m_columns[2] = ColumnBinder(&m_default_columns[2]);
+}
+
+void Bootloader::CrashMenu::post_open() {
+  // We override the open method
+  for (;;) {
+    // Infinite loop
+  }
+}
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/crash.cpp]: Add newline
```suggestion
}

```

File: bootloader/interface/menus/crash.h [hunk 43]
```diff
@@ -0,0 +1,19 @@
...
+
+      void setup() override;
+      void post_open() override;
+
+    private:
+      const char * m_error;
+  };
+}
+
+#endif
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/crash.h]: Add newline
```suggestion
#endif

```

File: bootloader/interface/menus/dfu.cpp [hunk 44]
```diff
@@ -0,0 +1,37 @@
...
+        forceExit();
+        return;
+      } else if (scan == Ion::Keyboard::State(Ion::Keyboard::Key::OnOff)) {
+        Ion::Power::standby();
+        return;
+      }
+    } while (!Ion::USB::isEnumerated());
+    Ion::USB::DFU(true, (void *)m_data);
+  }
+}
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/dfu.cpp]: Add newline
```suggestion
}

```

File: bootloader/interface/menus/home.cpp [hunk 45]
```diff
@@ -0,0 +1,144 @@
...
+const char * Bootloader::HomeMenu::slotKhi_kernel_text() {
+  return Slot::isFullyValid(Slot::Khi()) ? Slot::Khi().kernelHeader()->patchLevel() : nullptr;
+}
+
+const char * Bootloader::HomeMenu::slotKhi_os_text() {
+  if (Slot::isFullyValid(Slot::Khi())) {
+    if (Slot::Khi().userlandHeader()->isOmega() && Slot::Khi().userlandHeader()->isUpsilon()) {
+      return Messages::upsilonSlot;
+    } else if (Slot::Khi().userlandHeader()->isOmega()) {
+      return Messages::omegaSlot;
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/home.cpp]: On all slots, if the slot is Omega,but doesn't have a git commit, it is Khi.

File: bootloader/interface/src/menu.h [hunk 46]
```diff
@@ -0,0 +1,126 @@
...
+      const char * m_title;
+      const char * m_bottom;
+      bool m_centerY;
+      int m_margin;
+    private:
+      bool m_forced_exit;
+  };
+}
+
+#endif // _BOOTLOADER_MENU_H_
```
Comment (Yaya-Cout) [inline bootloader/interface/src/menu.h]: Add newline
```suggestion
#endif // _BOOTLOADER_MENU_H_

```

File: bootloader/interface/static/interface.cpp [hunk 47]
```diff
@@ -0,0 +1,68 @@
+
```
Comment (Yaya-Cout) [inline bootloader/interface/static/interface.cpp]: Remove newline
```suggestion
```

File: bootloader/interface/static/interface.h [hunk 48]
```diff
@@ -0,0 +1,19 @@
...
+
+public:
+  static void drawImage(KDContext * ctx, const Image * image, int offset);
+  static void drawLoading();
+  static void drawFlasher();
+};
+
+}
+
+#endif
```
Comment (Yaya-Cout) [inline bootloader/interface/static/interface.h]: Add newline
```suggestion
#endif

```

File: bootloader/interface/static/messages.h [hunk 49]
```diff
@@ -0,0 +1,93 @@
...
+class Messages {
+public:
+  // TODO: Remove it when this fork will be updated
+  #ifdef UPSILON_VERSION
+  constexpr static const char * mainTitle = "Upsilon Calculator";
+  #elif defined OMEGA_VERSION
+  constexpr static const char * mainTitle = "Omega Calculator";
+  #else
+  constexpr static const char * mainTitle = "NumWorks Calculator";
+  #endif
```
Comment (Yaya-Cout) [inline bootloader/interface/static/messages.h]:
```suggestion
  constexpr static const char * mainTitle = "Upsilon Calculator";
```

File: bootloader/main.cpp [hunk 50]
```diff
@@ -3,40 +3,59 @@
...
+#include <bootloader/interface/static/interface.h>
+#include <bootloader/slots/slot.h>
+#include <bootloader/slots/slot_exam_mode.h>
+#include <bootloader/recovery.h>
+#include <ion/src/device/shared/drivers/flash.h>
 
 __attribute__ ((noreturn)) void ion_main(int argc, const char * const argv[]) {
   // Clear the screen
-  Ion::Display::pushRectUniform(KDRect(0,0,320,240), KDColorBlack);
+  Ion::Display::pushRectUniform(KDRect(0,0,320,240), KDColorWhite);
```
Comment (Yaya-Cout) [inline bootloader/main.cpp]:
```suggestion
  Ion::Display::pushRectUniform(KDRect(0,0,320,240), KDColorBlack);
```

File: bootloader/interface/menus/home.cpp [hunk 51]
```diff
@@ -0,0 +1,144 @@
...
+    m_default_columns[1] = Column(Messages::homeAboutSubmenu, Ion::Keyboard::Key::Five, k_small_font, 10, false, &about_submenu);
+    
+
+    m_columns[0] = ColumnBinder(&m_slot_columns[0]);
+    m_columns[1] = ColumnBinder(&m_slot_columns[1]);
+    m_columns[2] = ColumnBinder(&m_slot_columns[2]);
+    m_columns[3] = ColumnBinder(&m_default_columns[0]);
+    m_columns[4] = ColumnBinder(&m_default_columns[1]);
+
+}
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/home.cpp]: Add newline
```suggestion
}

```

File: bootloader/interface/menus/installer.cpp [hunk 52]
```diff
@@ -0,0 +1,41 @@
...
+
+void Bootloader::InstallerMenu::setup() {
+    m_default_columns[0] = Column(Messages::installerText1, k_large_font, 0, true);
+    m_default_columns[1] = Column(Messages::installerSlotsSubmenu, Ion::Keyboard::Key::One, k_small_font, 30, false, &slots_submenu);
+    m_default_columns[2] = Column(Messages::installerBootloaderSubmenu, Ion::Keyboard::Key::Two, k_small_font, 30, false, &bootloader_submenu);
+
+    m_columns[0] = ColumnBinder(&m_default_columns[0]);
+    m_columns[1] = ColumnBinder(&m_default_columns[1]);
+    m_columns[2] = ColumnBinder(&m_default_columns[2]);
+}
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/installer.cpp]: Add newline
```suggestion
}

```

File: bootloader/interface/menus/installer.h [hunk 53]
```diff
@@ -0,0 +1,20 @@
...
+
+      void setup() override;
+      void post_open() override {};
+
+      static DfuMenu * SlotsDFU();
+      static DfuMenu * BootloaderDFU();
+  };
+}
+
+#endif
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/installer.h]: Add newline
```suggestion
#endif

```

File: bootloader/interface/menus/slot_recovery.cpp [hunk 54]
```diff
@@ -0,0 +1,39 @@
...
+        forceExit();
+        return;
+      } else if (scan == Ion::Keyboard::State(Ion::Keyboard::Key::OnOff)) {
+        Ion::Power::standby();
+        return;
+      }
+    } while (!Ion::USB::isEnumerated());
+    Ion::USB::DFU(true, (void *)m_data);
+  }
+}
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/slot_recovery.cpp]: Add newline
```suggestion
}

```

File: bootloader/interface/menus/slot_recovery.h [hunk 55]
```diff
@@ -0,0 +1,19 @@
...
+      SlotRecoveryMenu(USBData * usbData);
+
+      void setup() override;
+      void post_open() override;
+    private:
+      const USBData * m_data;
+  };
+}
+
+#endif
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/slot_recovery.h]: Add newline
```suggestion
#endif

```

File: bootloader/interface/menus/warning.cpp [hunk 56]
```diff
@@ -0,0 +1,35 @@
...
+    m_default_columns[4] = Column(Messages::epsilonWarningMessage5, Ion::Keyboard::Key::EXE, k_small_font, 0, true, &proceed);
+    m_default_columns[5] = Column(Messages::epsilonWarningMessage6, Ion::Keyboard::Key::Back, k_small_font, 0, true, &backoff);
+    
+    m_columns[0] = ColumnBinder(&m_default_columns[0]);
+    m_columns[1] = ColumnBinder(&m_default_columns[1]);
+    m_columns[2] = ColumnBinder(&m_default_columns[2]);
+    m_columns[3] = ColumnBinder(&m_default_columns[3]);
+    m_columns[4] = ColumnBinder(&m_default_columns[4]);
+    m_columns[5] = ColumnBinder(&m_default_columns[5]);
+}
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/warning.cpp]: Add newline
```suggestion
}

```

File: bootloader/interface/menus/warning.h [hunk 57]
```diff
@@ -0,0 +1,17 @@
...
+  class WarningMenu : public Menu {
+    public:
+      WarningMenu();
+
+      void setup() override;
+      void post_open() override {};
+  };
+}
+
+#endif
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/warning.h]: Add newline
```suggestion
#endif

```

**Review by Yaya-Cout — CHANGES_REQUESTED** [review]
Please remove `themes/themes/local/upsilon_light/bootloader/computer.xcf`

File: bootloader/interface/static/messages.h [hunk 58]
```diff
@@ -0,0 +1,86 @@
+#ifndef BOOTLOADER_INTERFACE_STATIC_MESSAGES_H
+#define BOOTLOADER_INTERFACE_STATIC_MESSAGES_H
+
+namespace Bootloader {
+
+class Messages {
+public:
+  constexpr static const char * mainTitle = "Upsilon Calculator";
+  
+  // home menu
```
Comment (Yaya-Cout) [inline bootloader/interface/static/messages.h]:
```suggestion
  // Home menu
```

File: bootloader/interface/static/messages.h [hunk 59]
```diff
@@ -0,0 +1,86 @@
...
+
+  constexpr static const char * aboutMessage1 = "This is the bootloader of";
+  constexpr static const char * aboutMessage2 = "the Upsilon Calculator.";
+  constexpr static const char * aboutMessage3 = "It is used to install";
+  constexpr static const char * aboutMessage4 = "and select the OS";
+  constexpr static const char * aboutMessage5 = "to boot.";
+
+  constexpr static const char * bootloaderVersion = "Version 1.0.0 - FREED0M";
+
+  //USB NAMES
```
Comment (Yaya-Cout) [inline bootloader/interface/static/messages.h:77]: Why do you use capitals letters ?

Comment (devdl11) [reply bootloader/interface/static/messages.h:77]: Because it's more stylish😎😎

File: bootloader/interface/menus/dfu.h [hunk 60]
```diff
@@ -0,0 +1,21 @@
...
+      void setup() override;
+      void postOpen() override;
+
+    private:
+      const char * m_submenuText;
+      const USBData * m_data;
+  };
+}
+
+#endif
```
Comment (Yaya-Cout) [inline bootloader/interface/menus/dfu.h]:
```suggestion
#endif

```

File: bootloader/boot.cpp [hunk 61]
```diff
@@ -1,66 +1,153 @@
...
-  if (mode > 3)
-    return Unknown;
+void Boot::setMode(BootMode mode) {
+  // We dont use the exam mode driver as storage for the boot mode because we need the 16k of storage x)
+}
 
-  return (BootMode) mode;
+void Boot::busError() {
+  // Ion::Device::Flash::DisableInternalProtection();
+  // Ion::Device::Flash::EraseSector(0);
```
Comment (Yaya-Cout) [inline bootloader/boot.cpp]: Remove comments if unused (below too)
```suggestion
```

Comment (devdl11) [reply bootloader/boot.cpp]: it's for the next update x)

Comment (devdl11) [reply bootloader/boot.cpp]: But I think i found something out
